include ../../Makefile.common

# You can override the default test if you want. (e.g. setup envtest)
# If you override, you're responsible for catching up the original updates.
# 
# .PHONY: common/test/go
# common/test/go:
# 	XXX=YYY go test -failfast -race ./...
